### ISSUE TITLE
Possible communication discussion

### ISSUE THREAD

**Issue by MalteT** [Hackspace-Leipzig-TheGame/Documentation#1]
# Websockets
If been tinkering with websockets a bit, since we've decided to use them somehow. There seem to be two possible transmission variants, `text` and `binary`. I'm not sure which one to use here, sending JSON UTF8 over binary is of course possible, but where's the point?

As I understood the discussion so far, we will be using JSON over a websocket (possibly `text` mode). This leads to the question

## How much websocket?
We could very well expose only `/ws` in the backend, handle a http upgrade and write the entire protocol as json communiication. The alternative would be to have additional http endpoints. Since we're using websockets anyway I don't see any reason against the first approach.. Opinions?

# Communication protocol
After settling on the basics, we should really discuss a high-level view of the communication process. I'm not sure how to approach this, but here are some messages that will have to be sent between `F`rontend and `B`ackend:

- `F -> B` I'd like a new session
  `B -> F` Here's the token/url, have fun
- `B -> F` Someone send 🤔 to the chat at time X
- `B -> F` Ping (Might also be doable by observing if the socket has been closed, not sure)
  `F -> B` Pong (translated: Don't kill me, don't forget me, don't drop me from the game)
- `B -> F` You're next (not sure about this one either)
  `F -> B` I'll put this 90 on deck 1
- `B -> F` Here's the new game state

This list is probably not complete, some of the above could also have additional messages. Some could also have 'Requests' like the game state update:
- `F -> B` Hey, I garbage collected everything, do you mind updating me?
  `B -> F` Here's the new game state

Just a few thoughts to get the discussion started :)

**Comment by mgutsche** [comment]
:+1:

**Comment by MalteT** [comment]
Superseded by #3
