### ISSUE TITLE
RFC #2 - Websocket Specification

### ISSUE THREAD

**Issue by zwisler-a** [Hackspace-Leipzig-TheGame/Documentation#3]
# RFC Websocket Specification Proposal - 0.0.1

> A websocket only specification.

# TOC
- [Authentication](#Authentication)
- [API](#api)
    - [Party API](#party-api)
    - [Game API](#game-api)
    - [Chat API](#chat-api)
- [Workflows](#workflows)

# General
The API is versioned by the Websocket path by the major version identifier with the prefix `ws/v`. Meaning, since this is Version `0.0.1` the major verion of the specification is 0. Resulting in a websocket path `ws/v0`. This means a valid websocket url for this api version would be something along the lines `ws://super-host.dev/ws/v0`.

# Authentication
To make sure no user can immitate another user, specific actions are secured by a simple "authentication". This authentication is not permanant and should not require an account or anything else besides a username. To acomplish this we use [JWT](https://jwt.io/introduction). A Token is created when a user joins a party and is used to authenticate chat messages and game actions. The API Calls, which should be checked by the server are marked with `Authentication needed`. 

### JWT Payload
| Property | Type | Description |
| ---      | ---  | ----        |
| username       | string | Username |
| partyId     | string | Identifier of the party |

# API
## Event base type
> The event base type is the form in which all events are sent

| Property | Type | Description |
| ---      | ---  | ----        |
| id       | string | UUID identifier
| type     | string | Identifier of the type of event. An event type consists of the scope of the event and the eventname itself seperated by a `/`. Example: `PARTY/CREATE_PARTY` |
| data     | EventData | `Optional` Containts additional information about the event |

# Party API
> This scope of the api allows players to create and join game parties.

## CreatePartyEvent
>  Event used to trigger the creation of a new party

type: `"PARTY/CREATE_PARTY"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| owner    | string | Identifier of the user which created the party

#### Example:
``` json
{
    "id": "c215d541-0237-4858-af39-dd39aa685c48",
    "data": {
        "type": "PARTY/CREATE_PARTY",
        "owner": "username"
    }
}
```

## PartyCreatedEvent
>  Server response when a party is successfully created. `Only gets send to the user who created the party`

type: `"PARTY/PARTY_CREATED"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| responseTo| string | EventID of the event which triggered the party creation |
| partyId    | string | Identifier of the created party. The should be a 4 random character string only containing [A-Z][a-z][0-9]. This allows users to manually input the partyId to join other parties. |
| authToken | string | JWT (See authentication) Giving the player a way to authenticate its actions in the party. |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "PARTY/PARTY_CREATED",
    "data": {
        "responseTo": "c215d541-0237-4858-af39-dd39aa685c48",
        "partyId": "BeEf",
        "authToken" : "ey[...]"
    }
}
```

## JoinPartyEvent
> Register a user and join the party

type: `"PARTY/JOIN"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| username    | string | Username, must be unique since users are identified by this |
| partyId    | string | ID of the Party to join |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "PARTY/JOIN",
    "data": {
        "username": "username",
        "partyId": "BeEf"
    }
}
```

## RejoinPartyEvent 
> Used the rejoin a party after a lost connection using the autentication JWT

`Authentication needed`

type: `"PARTY/REJOIN"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| authToken    | string | JWT |
| partyId    | string | ID of the Party to join |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "PARTY/REJOIN",
    "data": {
        "authToken": "ey[...]",
        "partyId": "BeEf"
    }
}
```

## PartyJoinedEvent
>  Server response when a party is successfully joined. `Only gets send to the user who requested to join/rejoin a party`

type: `"PARTY/PARTY_CREATED"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| responseTo| string | EventID of the PartyJoinEvent which triggered the party join |
| authToken | string | JWT (See authentication) Giving the player a way to authenticate its actions in the party. |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "PARTY/PARTY_CREATED",
    "data": {
        "responseTo": "c215d541-0237-4858-af39-dd39aa685c48",
        "partyId": "BeEf",
        "authToken" : "ey[...]"
    }
}
```

## StartGameEvent
> Send by the owner of the party to start the game

`Authentication needed`

type: `"PARTY/START"`

| Property | Type | Description |
| ---      | ---  | ----        |
| authToken | string | JWT (See authentication) Giving the player a way to authenticate its actions in the party. |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "PARTY/START",
    "data": {
        "authToken": "ey[...]"
    }
}
```

# Game API

## GameStateEvent
> Gives the current game state to the users. Needs to be personalized since the hands of the players should not be accessable to other players. Gets sent on ever step of the game: Game start, Each Round ...

type: `"GAME/STATE"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| activePlayer | string | `Optional` Username of the player whos turn it is. If the active player is `null` or `undefined` the player to start the turn must be voted (see PlayerStartVoteEvent) |
| payerHand | Card[] | (see Card) The current Hand of the player which receives this event |
| playersCardsCount | Map<String, Number> | Contains the number of cards each player has. This is represented in a map where the key is the username and the value is the amount of cards. |
| stacks | Stack[] | The card stacks in the game a player can deposit cards on |
| drawStackCardCount | number | Amount of cards left in the stack where players have to draw cards |

#### Card
| Property | Type | Description |
| ---      | ---  | ----        |
| value | number | Numerical value the card has |
| id | number | Identifier of the card. (Not sure if this is necessary ... only if there are multiple cards with the same value)|

#### Stack
| Property | Type | Description |
| ---      | ---  | ----        |
| id       | number | Identifier of the stack
| ascending | boolean | Determines if the cards in the stack need to be in the acending ot decending order
| currentValue | number | Numerical value of the current value of the stack |

#### Example
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "GAME/STATE",
    "data": {
        "activePlayer": "username",
        "playerHand": [
            { "id":1, "value": 1 },
            { "id":3, "value": 3 },
            { "id":3, "value": 3 },
            { "id":7, "value": 7 },
            { "id":4, "value": 4 },
            { "id":2, "value": 2 },
        ],
        "playerCardsCount" : {
            "username": 6,
            "username2": 6,
            "username3": 4
        },
        "stacks": [
            { "id": 1, "ascending": false, "currentValue":87 },
            { "id": 2, "ascending": false, "currentValue":51 },
            { "id": 3, "ascending": true, "currentValue":2 },
            { "id": 4, "ascending": true, "currentValue":5 },
        ],
        "drawStackCardCount": 94
    }
}

```

## PlayCardsEvent
>  Sent by a player to deposit cards on the stack

`Authentication needed`

type: `"GAME/PLAY"`

Also the game needs to check if the player sending the event has the current turn.

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| authToken | string | JWT (See authentication) |
| actions | Action[] | Actions the player whishes to perform |

#### Action
| Property | Type | Description |
| ---      | ---  | ----        |
| cardId   | number | Id the of card to play |
| stackId   | number | Id of the stack the card should land on |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "GAME/PLAY",
    "data": {
        "authToken" : "ey[...]",
        "actions": [
            { "cardId": 1, "stackId": 1 },
            { "cardId": 97, "stackId": 3 }
        ]
    }
}
```

## PlayerStartVoteEvent
>  Send by a client to vote which player starts

type: `"GAME/VOTE"`

| Property | Type | Description |
| ---      | ---  | ----        |
| nominee | string | Username of the player which is voted for |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "GAME/VOTE",
    "data": {
        "nominee": "username"
    }
}
```

## RequestStateEvent
>  Send by a client which, for whatever reason (reconnect etc ...), has lost the current game state. Triggers a resend of the GameStateEvent on the server

type: `"GAME/REUQST_STATE"`

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "GAME/REUQST_STATE",
}
```

## PlayerLostEvent
>  Sent if a play is not able to play any other cards and has lost the game.

type: `"GAME/PLAYER_LOST"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| loser | string | Username of the player who lost the game |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "GAME/PLAYER_LOST",
    "data": {
        "loser": "username"
    }
}
```

## PlayerWonEvent
>  Sent if a play is not able to play any other cards and has lost the game.

type: `"GAME/PLAYER_WON"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| winner | string | Username of the player who won the game |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "GAME/PLAYER_WON",
    "data": {
        "loser": "winner"
    }
}
```

# Chat API

## Sent Message Event
>  An event sent from the user to the server to send a message

`Authentication needed`

type: `"CHAT/SEND_MESSAGE"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| authToken | string | JWT (See authentication) |
| message | string | The message the user wants to sent |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "GAME/PLAY",
    "data": {
        "authToken" : "ey[...]",
        "message": "Hi there"
    }
}
```

## Message Event
>  An event sent from the user to the server to send a message

type: `"CHAT/MESSAGE"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| username | string | username of the user which sent the message - extracted from the JWT in `MESSAGE/SENT_MESSAGE` |
| message | string | The message the user wants to sent |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "CHAT/MESSAGE",
    "data": {
        "username" : "grievous",
        "message": "General Kenobi"
    }
}
```

# Error Events

## PartyNotFoundError
>  Sent if the party if does not exist. Only gets sent to the socket request to join a party

type: `"ERROR/PARTY_NOT_FOUND"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| responseTo| string | EventID of the triggering Event |
| partyId | string | Id of the non existent party |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "ERROR/PARTY_NOT_FOUND",
    "data": {
        "responseTo": "c215d541-0237-4858-af39-dd39aa685c48",
        "partyId": "BeEf",
    }
}
```

## InvalidPlayError
>  Sent if the play of a user is invalid

type: `"ERROR/INVALID_PLAY"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| responseTo| string | EventID of the triggering Event |
| reason | string | Textform Error message. Might be usefull to specifiy the error cases in more detail ... |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "ERROR/INVALID_PLAY",
    "data": {
        "responseTo": "c215d541-0237-4858-af39-dd39aa685c48",
        "reason": "BeEf",
    }
}
```

## AuthenticationError
>  Sent if the authentication of a user is invalid

type: `"ERROR/AUTEHNTICATION"`

#### EventData
| Property | Type | Description |
| ---      | ---  | ----        |
| responseTo| string | EventID of the triggering Event |
| reason | string | Textform Error message. Might be usefull to specifiy the error cases in more detail ... |

#### Example:
``` json
{
    "id": "bff793ff-5cfe-46de-bc28-3a47f7a3ce2e",
    "type": "ERROR/AUTEHNTICATION",
    "data": {
        "responseTo": "c215d541-0237-4858-af39-dd39aa685c48",
        "reason": "BeEf",
    }
}
```

# Workflows

(This probably should be nice graphics but well ... here are some lists ...)

## Party creation and joining
> A User creates a new party, invites friends which join the party and starts the game.

- User1 sends `CreatePartyEvent`
    - Server creates a new Party (Local container in which all websocket connections are hold which belong to a party)
    - Server sends `PartyCreatedEvent` to User1
- User1 receives `PartyCreatedEvent` 
    - User1 stores JWT locally
- User1 shares partyId with User2
- User2 joins party with `JoinPartyEvent` with partyId and a username
    - Server recvieves event and creates a JWT for the user
    - Server puts the connection into the container assicated with the party
    - server sends `PartyJoinedEvent` to User2
- User2 recvieves `PartyJoinedEvent`
    - User2 stores JWT locally
    - User2 waits for the game to be started
- User1 start the game with `StartGameEvent`
    - Server creates a new GameState for the current party.
    - A `GameStateEvent` is sent to each user containing the GameState for the specific user
        - (The activeUser object in the `GameStateEvent` is null/undefined. This indicates the start-voting-mechanism)

## Player Voting to start
> Continuuation of "Party creation and joining" with User1 and User2

- Players recieve a `GameStateEvent` with empty activePlayer
- User1 selects a Player to start
    - User1 sends `PlayerStartVoteEvent` with the selected nominee
- User2 selects a Player to start
    - User2 sends `PlayerStartVoteEvent` with the selected nominee
- Server recieved a `PlayerStartVoteEvent` from each user
    - Server sends a `GameStateEvent` where the user with the most votes is the "activePlayer"

# Player turn
> 

- Player recieves a `GameStateEvent` where the "activePlayer" object is the Player
- Player selects cards to put on the stacks
    - Player sends `PlayCardsEvent` with the cards and the corresponding stacks
- Server receives `PlayCardsEvent`
    - Server validates the JWT and checks if the player has the turn
    - Server calculates new GameState
    - Server sends new `GameStateEvent` with new active player
- Player recvieves new GameState and waits ...

# Player has no cards left
- Player recieves a `GameStateEvent` where the "activePlayer" object is the Player
- Player selects cards to put on the stacks
    - Player sends `PlayCardsEvent` with the cards and the corresponding stacks
- Server receives `PlayCardsEvent`
    - Server validates the JWT and checks if the player has the turn
    - Server calculates new GameState
        - Server notices empty drawStack and no cards left in player hand
        - Server send `PlayerWonEvent` to all Players
    - Server sends new `GameStateEvent`

# Player cant play anymore
- Player recieves a `GameStateEvent` where the "activePlayer" object is the Player
- Player selects cards to put on the stacks
    - Player sends `PlayCardsEvent` with the cards and the corresponding stacks
- Server receives `PlayCardsEvent`
    - Server validates the JWT and checks if the player has the turn
    - Server calculates new GameState
        - Server notices Player cant play any cards
        - Server send `PlayerLostEvent` to all Players
    - Server sends new `GameStateEvent`

# Player makes an invalid move
 Player recieves a `GameStateEvent` where the "activePlayer" object is the Player
- Player selects cards to put on the stacks
    - Player sends `PlayCardsEvent` with the cards and the corresponding stacks
- Server receives `PlayCardsEvent`
    - Server validates the JWT and checks if the player has the turn
    - Server notices an invalid move (eg. only one card played while drawStack > 0)
    - Server sends a `InvalidPlayError` to Player
    - Server waits for new Play from user ...

# Player sends a chat message
- Player sends a `SendMessageEvent`
- Server receives a `SendMessageEvent`
    - Server validates the JWT
    - Server checks if the message contains any illigal characters (see #2)
    - Server creates a `MessageEvent` with the username in the JWT
    - Server sends the event to all users in the party

**Comment by MalteT** [comment]
Seeing that you took the RFC process more seriously than I did, I propose to move this to a PR, to make it simpler for people to comment on the details. (I removed my "MVP" and created #4)

This looks very promissing already, thanks for your work!

**Comment by zwisler-a** [comment]
Moved to PR #5
